# Generated by Django 5.1.3 on 2024-11-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
            options={
                'permissions': [('can_view', 'Can view articles'), ('can_edit', 'can_edit_articles'), ('can_delete', 'can delete articles')],
            },
        ),
    ]
